### PR TITLE
Extend the ACME Order object with the ARI Payload

### PR DESCRIPTION
**Pull request by jvanasco**
My idea for #42

1.  Added a subsection "### Extending ACME Order Objects with ARI"
2.  Added an "Interoperability Considerations" section.  I've seen this in a handful of specs over the years.  

Notes:

1. I just defined the fields with "as defined in the aforementioned `renewalInfo` resource"
2. The only messy thing about this approach is we have "Retry-After" as a header on the resource URL, and it's migrated to a "retryAfter" field within the account object.  I don't like that, but I dislike even more the idea of making the "Retry-After" header a field in the resource URL.

### CODE REVIEW

**Comment by aarongable** [comment]
Now that I've merged https://github.com/aarongable/draft-acme-ari/pull/51, I think I'm much more amenable to including something like this in the next version. Want to update this to match the new layout (especially the IANA Considerations section)?

**Comment by jvanasco** [comment]
Sure. I'll try to get to it today or tomorrow.

**Comment by jvanasco** [comment]
Resubmitted via a force-push, as the other options were merge-commits or a new PR.

Note: in two places ("Interoperability Considerations" and "ACME Order Object Fields"), `renewalInfo` was added above `replaces` for alphabetical ordering.

**Comment by aarongable** [comment]
At this point I no longer believe that this extension is necessary. It saves a grand total of one ARI query across the lifetime of the certificate, adds per-certificate information to the Order object (which causes issues with multi-cert-per-order extensions like ACME STAR), and co-mingles two different ACME resources inside a single object (which is done nowhere else in the protocol). As such I think I'm going to abandon this potential change. Thank you for the idea and work!

**Pull request closed without merging**
